{{- if .Values.persistence.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.persistence.dags.name }}
spec:
  accessModes:
    - {{ .Values.persistence.dags.accessMode }}
  capacity:
    storage: {{ .Values.persistence.dags.size }}
  hostPath:
    path: {{ .Values.persistence.dags.path }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.dags.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.dags.size }}

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.persistence.logs.name }}
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessMode }}
  capacity:
    storage: {{ .Values.persistence.logs.size }}
  hostPath:
    path: {{ .Values.persistence.logs.path }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.logs.name }}
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}

{{- end }}

