---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: admin-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: {{default default .Values.rbac.namespace }}
    # Reference to upper's `metadata.namespace`
    namespace: {{default default .Values.rbac.namespace }}
roleRef:
  kind: {{ default ClusteRole .Values.rbac.role.kind  }}
  name: {{ default cluster-admin .Values.rbac.role.name   }}
  apiGroup: {{ default rbac.authorization.k8s.io .Values.rbac.role.apiGroup }}
  